version: "3"

services:
  # rails
  app:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  
  # nginx
  web:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - /tmp/sockets:/app/tmp/sockets
    depends_on:
      - app
